providers:
  - airtap-sauce
browsers:
  - name: chrome
    version: '-2..latest'
  - name: firefox
    version: '-2..latest'
  - name: safari
    version: '-2..latest'
  - name: microsoftedge
    version: '-2..latest'
  - name: iphone
    version: '-2..latest'
  - name: android
    version: '-2..latest'
browserify:
  - plugin:
      - esmify
presets:
  local:
    providers: airtap-manual
    browsers:
      - name: manual
